### ISSUE TITLE
Site not working

### ISSUE THREAD

**Issue by TheTechRobo** [OpenShopChannel/WSC-Docs#1]
https://wsc-docs.oscwii.org/ does not work.

**Comment by dakrk** [comment]
The URL shown in the repository is wrong, it's actually https://wiishop-docs.oscwii.org/

**Comment by TheTechRobo** [comment]
@dakrk Ah thanks! That should be updated.

**Comment by dhtdht020** [comment]
Thanks for bringing this to our attention, this was now corrected.

**Comment by TheTechRobo** [comment]
Now it says "There isn't a GitHub Pages site here"...It seems to now be https://docs.oscwii.org/wii-shop-channel/.

**Comment by spotlightishere** [comment]
Oops - we changed things around. Should be good now!
