### ISSUE TITLE
How to view internal C++ types

### ISSUE THREAD

**Issue by Ocarinaoftime** [OpenShopChannel/WSC-Docs#5]
Make a tutorial to extract the C++ types from the Wii Shop Channel title contents to help with revivals know what each function is really doing on a programming standpoint.

**Comment by Naim2000** [comment]
> to help with revivals

No

**Comment by dakrk** [comment]
For what reason? If you're wanting to do binary patches, I'd be interested knowing what else there is to patch.

**Comment by Ocarinaoftime** [comment]
I just want a better understanding of what each function does in Opera.

**Comment by Ocarinaoftime** [comment]
Btw I accidentally closed the issue so it’s still open.

**Comment by Puppercino** [comment]
> I just want a better understanding of what each function does in Opera.

WSC-Docs' intention is to provide documentation for the WSC's Javascript APIs and SOAP Schemas it used. 
While documenting the inner workings of WSC's browser would be a nice-to-have, it's a major task and probably out of scope for this repository. 

If you have experience in reverse engineering and want to help out, I encourage you to unpack the APP (using a RARC extractor) files and use Ghidra to try and inspect the WSC binaries yourself. 

GLHF :3 

![cat_curious](https://github.com/OpenShopChannel/WSC-Docs/assets/19499924/6a766b9b-3163-4126-92e4-d6c18e7b46a6)

**Comment by dakrk** [comment]
00000002.app (or 0000005f.app as it is in NAND) contains a `main.sel` file which contains many symbols. However, I don't remember how these files would be imported into Ghidra, only IDA.

**Comment by Ocarinaoftime** [comment]
> only IDA

what is IDA? Just so I know what to look up unless I can just search up “IDA Wii”

**Comment by Artuto** [comment]
This is outside the scope of this repository.
